baseURL = "http://localhost/"
languageCode = "de-de"
title = "3d Druck - meine Aufzeichnungen "

theme = "hugo-lithium-theme"

[params]
    mainSections = ["post"]

    description = ""

    # path to the favicon, under "static"
    favicon = "favicon.ico"

    [params.logo]
    url = "logo.png"
    width = 50
    height = 50
    alt = "Logo"

    [params.icon]
    url = "favicon.ico"